on:
  push:
    branches: ["yulia_bezginova"]
  schedule:
    - cron: "0 */1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
      - name: "python script"
        env:
          TW_ACCESS_TOKEN: ${{ secrets.TW_ACCESS_TOKEN }}
          TW_ACCESS_TOKEN_SECRET: ${{ secrets.TW_ACCESS_TOKEN_SECRET }}
          TW_CONSUMER_KEY: ${{ secrets.TW_CONSUMER_KEY }}
          TW_CONSUMER_KEY_SECRET: ${{ secrets.TW_CONSUMER_KEY_SECRET }}
          MONGODB_USER: ${{ secrets.MONGODB_USER }}
          MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
          MONGO_DB_ADDRESS: ${{ secrets.MONGO_DB_ADDRESS }}
        run: |
          main.py